### ISSUE TITLE
Checklist of missing items:

### ISSUE THREAD

**Issue by Jflamencoktt** [psi-mis/jobAid#105]

**Comment by Jflamencoktt** [comment]
Items:

- [ ] Gamo Videos
- [ ] Gamo MP3
- [ ] New Group Session Screen design for Data Capture

Updated 6/21/2022

- [x] Sidama Videos
- [x] Sidama MP3
- [x] NEW Thumbnails Oromiffa/Amharic
- [x] RSS11 Re-design
- [x] Spacing for Babies Video re-issue
- [x] Translations 100% Sidama
- [x] Translation 100% Gamo
